#For product service 
spring:
  datasource:
    url: ${db_url}
    username: ${db_username}
    password: ${db_password}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: ${eureka_url}
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${random.value}
